[package]
name    = "doppelganger"
version = "0.1.0"
edition = "2024"

[dependencies]
csv   = "1.3"
serde = { version = "1.0", features = ["derive"] }
time  = { version = "0.3", features = ["parsing", "serde"] }
